media:
  - name: assets
    label: Assets
    input: static/assets
    output: /assets
  - name: gallery
    label: Gallery
    input: static/media
    output: /media
    categories: [image, video]

content:
  - name: rules
    label: RP Rules Page
    type: file
    path: static/content/rules.md
  - name: conduct
    label: Community Standards Page
    type: file
    path: static/content/conduct.md
  - name: history-of-vardoran
    label: Lore - History of Vardoran
    type: file
    path: static/content/lore-history-of-vardoran.md
  - name: species
    label: Lore - Species
    type: file
    path: static/content/lore-species.md
  - name: beyond-vardoran
    label: Lore - Beyond Vardoran
    type: file
    path: static/content/lore-beyond-vardoran.md
  - name: religions
    label: Lore - Religions
    type: file
    path: static/content/lore-religions.md
  - name: realms
    label: Lore - Realms
    type: file
    path: static/content/lore-realms.md
  - name: guides
    label: Guides Page
    type: collection
    path: static/content/guides
    format: json
    filename: '{primary}.json'
    exclude: ['guides-index.json']
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: content
        label: Content
        type: text
  - name: guides-index
    label: Guides Index Page
    type: file
    format: json
    path: static/content/guides/guides-index.json
  - name: media-gallery
    label: Media Gallery
    type: collection
    path: static/content/media
    format: json
    filename: '{primary}.json'
    exclude: ['media-index.json']
    fields:
      - name: title
        label: Title
        type: string
      - name: src
        label: Image
        type: image
        options:
          media: gallery
      - name: type
        label: Type
        type: string
      - name: alt
        label: Alt text
        type: string
      - name: caption
        label: Caption
        type: string
  - name: media-index
    label: Media Index
    type: file
    format: json
    path: static/content/media/media-index.json

settings:
  content:
    merge: true
