media:
  input: src/lib/media
  output: /media

content:
  - name: rules
    label: Rules Page
    type: file
    path: static/content/rules.md

lore:
  - name: origins
    label: Origins
    type: file
    path: static/content/lore-origins.md
  - name: factions
    label: Factions
    type: file
    path: static/content/lore-factions.md

settings:
  content:
    merge: true