media:
  input: static/media
  output: static/media

content:
  - name: rules
    label: Rules Page
    type: file
    path: static/content/rules.md
  - name: history-of-vardoran
    label: Lore - History of Vardoran
    type: file
    path: static/content/lore-history-of-vardoran.md
  - name: species
    label: Lore - Species
    type: file
    path: static/content/lore-species.md
  - name: beyond-vardoran
    label: Lore - Beyond Vardoran
    type: file
    path: static/content/lore-beyond-vardoran.md
  - name: religions
    label: Lore - Religions
    type: file
    path: static/content/lore-religions.md
  - name: realms
    label: Lore - Realms
    type: file
    path: static/content/lore-realms.md
  - name: guides
    label: Guides Page
    type: collection
    path: static/content/guides
    format: json
    filename: '{primary}.json'
    exclude: [ 'guides-index.json']
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: content
        label: Content
        type: rich-text
  - name: guides-index
    label: Guides Index Page
    type: file
    path: static/content/guides/guides-index.json

settings:
  content:
    merge: true